services:
  blogapp.api:
    image: blogapp.api
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/BlogApp.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - sqlserver
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - EmailSettings__SmtpServer=${EmailSettings__SmtpServer}
      - EmailSettings__SmtpPort=${EmailSettings__SmtpPort}
      - EmailSettings__SmtpSenderEmail=${EmailSettings__SmtpSenderEmail}
      - EmailSettings__SmtpUsername=${EmailSettings__SmtpUsername}
      - EmailSettings__SmtpPassword=${EmailSettings__SmtpPassword}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd123
      - MSSQL_PID=Developer
    volumes:
      - sqlserverdata:/var/opt/mssql
    #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Passw0rd123", "-Q", "SELECT 1" ]
      start_period: 60s  # Extra time for ARM initialization

volumes:
  sqlserverdata:
