services:
  blogapp.api:
    image: blogapp.api
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/BlogApp.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - sqlserver
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - EmailSettings__SmtpServer=${EmailSettings__SmtpServer}
      - EmailSettings__SmtpPort=${EmailSettings__SmtpPort}
      - EmailSettings__SmtpSenderEmail=${EmailSettings__SmtpSenderEmail}
      - EmailSettings__SmtpUsername=${EmailSettings__SmtpUsername}
      - EmailSettings__SmtpPassword=${EmailSettings__SmtpPassword}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd123
      - MSSQL_PID=Developer
    volumes:
      - sqlserverdata:/var/opt/mssql
    #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Passw0rd123", "-Q", "SELECT 1" ]
      start_period: 60s  # Extra time for ARM initialization

volumes:
  sqlserverdata:
    
    
#TODO
## Add github actions or azure devops ci/cd -> Done ✔️
## Use production environment and setup real db in azure not use development -> Done ✔️
## Explore queues in sending emails -> Done ✔️
## Add a readme file -> Done ✔️
## Add seed data for database Done ✔️
## Add Cors support -> Done ✔️
## Add [Authorize] to top of each controller to authorize all the endpoints -> Done✔️
## Add ApiController to all the controllers to handle the model state and remove all the modelstates -> Done ✔️
## Implement api versioning -> Done ✔️
## Remove user file from the root folder Done ✔️
## Move AZURE_WEBAPP_URL to github actions secrets -> Done ✔️
## Update hangfire endpoint in azure deployed app to work -> Done ✔️
## Add database ERD diagram to the project
## Add licence
